name: CI/CD Pipeline
on:
  push:
    branches: ['main']
    tags: ['v[0-9]+.[0-9]+.*']

jobs:
  push-to-branch:
    name: Push to Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Push
        run: |
          git --no-pager branch
          git --no-pager log --oneline
          echo "${{ github.ref_name }}"
          echo "${{ github.sha }}"
          echo "Done!"